version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://dummyjson.com
    volumes:
      - .:/app
    restart: unless-stopped
